env:
  browser: true
  es6: true

extends: 'eslint:recommended'

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

  sourceType: module

plugins:
  - react

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - never

  padded-blocks:
    - error
    - never

  padding-line-between-statements:
    - error
    - always

  space-infix-ops:
    - error
    - always

  key-spacing:
    - error

    singleLine:
      beforeColon: false
      afterColon: true

    align:
      beforeColon: false
      afterColon: false
      on: value
